### ISSUE TITLE
Division by zero error

### ISSUE THREAD

**Issue by emmakwiener** [Genotek/ClassifyCNV#6]
Good day,
I have been trying to run ClassifyCNV and have had the following error.
Traceback (most recent call last):
  File "ClassifyCNV.py", line 834, in <module>
    analyze_pop_freqs()
  File "ClassifyCNV.py", line 737, in analyze_pop_freqs
    overlap_perc = int(fields[9]) * 100 / (int(fields[2]) - int(fields[1]))
ZeroDivisionError: division by zero
I used this command `python3 ClassifyCNV.py --infile MTDDgene.bed --GenomeBuild hg38` and here is the beginning of the bed file.

chr1	1339884	1339884	DUP	78
chr1	1450954	1516361	DUP	65407
chr1	1478376	1517082	DUP	38706
chr1	1484927	1522741	DUP	37814
chr1	1529887	1529962	DEL	75
chr1	1530531	1530850	DEL	319
chr1	1532785	1532785	DUP	54
chr1	1842391	1848340	DEL	5949
chr1	2230766	2231750	DEL	984
chr1	2309634	2309829	DEL	195
chr1	3848063	3848421	DEL	358
chr1	5868308	5868634	DEL	314
chr1	5959500	5959580	DEL	80

Could you please assist me is resolving this?
Thank you so much
Regards
Emma

**Comment by emmakwiener** [comment]
Realised the DUP INS were the problem, with the same start and end coordinates
