### ISSUE TITLE
Error in code

### ISSUE THREAD

**Issue by Danigore25** [Genotek/ClassifyCNV#9]
Hi, I tried to run ClassifyCNV by Python3 from my Linux terminal, but the output told me that it was an error in position 4 with a decode byte 0xa8. I searched it in the web but I can't solve this problem. Could you assist me with this?

**Comment by tgurbich** [comment]
Hi! Could you please paste the full command you were running and the entire error message (full output from the terminal)?

**Comment by Danigore25** [comment]
Of course. The full command is:
python3 ClassifyCNV.py --infile ../../MxGDAR_Nofilters.bed --GenomeBuild hg38 --precise

And the error message is:
ClassifyCNV.py Version 1.1.1
Traceback (most recent call last):
  File "ClassifyCNV.py", line 821, in <module>
    cnv_list = parse_infile(infile_path)  # save each CNV as chr_start_end_type and print a new file for BEDTools
  File "ClassifyCNV.py", line 87, in parse_infile
    for line in bed_infile:
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa8 in position 4: invalid start byte

**Comment by tgurbich** [comment]
Thank you. Would you mind also sharing the input file you are using (MxGDAR_Nofilters.bed)?

**Comment by Danigore25** [comment]
I'm sorry, but I'm not capable to share the input file. Although, I can describe you the structure of it.
With the command xxd -b, I could visualize my file .bed, and I found a series of eight columns. In the first one I have eight digits (some of them could be letters) and then two points. Next, I have six columns with a code compounded by 0's and 1's and a final column with a security code (with points and other characters).

**Comment by tgurbich** [comment]
Could you please check that when viewing your input file as text, not as bit strings, the only characters within the file (besides empty space) are digits and words "chr", "DEL", "DUP"?  The input file should look like this: https://raw.githubusercontent.com/Genotek/ClassifyCNV/master/Examples/1000Genomes.hg38.bed
